# Generated by Django 5.2.6 on 2025-09-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
    ]
