# Generated by Django 5.2.6 on 2025-09-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model']},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'driver', 'verbose_name_plural': 'drivers'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
    ]
